from snakemake.utils import min_version

min_version("7.25.0")


include: "rules/common.smk"


module reads_workflow:
    snakefile:
        github("cuspuk/workflow_reads", path="workflow/Snakefile", tag=config["module_versions"]["reads"])
    config:
        config


use rule * from reads_workflow as reads_*


for field in ["assembly", "classification", "report"]:
    for tool in config["assembly"][field]:

        include: f"rules/{field}/{tool}.smk"


rule all:
    input:
        **get_outputs(),
    default_target: True
    localrule: True
