"$schema": http://json-schema.org/draft-06/schema#
"$ref": "#/definitions/AssemblyWorkflow"
definitions:
  AssemblyWorkflow:
    type: object
    additionalProperties: true
    properties:
      max_threads:
        type: integer
        description: "Number of maximum threads to use in jobs"
        default: 1
      max_mem_mb:
        type: integer
        description: "Maximum memory in megabytes to allocate for any job"
        default: 2048
      assembly:
        type: object
        "$ref": "#/definitions/Assembly"
      assembly__assembly__spades:
        type: object
        "$ref": "#/definitions/AssemblyAssemblySpades"
      assembly__report__quast:
        type: object
        "$ref": "#/definitions/AssemblyReportQuast"
      assembly__classification__blast:
        type: object
        "$ref": "#/definitions/AssemblyClassificationBlast"
      resources:
        type: object
        "$ref": "#/definitions/Resources"
      threads:
        type: object
        "$ref": "#/definitions/Threads"
      module_versions:
        type: object
        "$ref": "#/definitions/ModuleVersions"
    required:
      - resources
      - threads
      - max_threads
      - max_mem_mb
      - assembly__classification__blast
      - assembly__assembly__spades
      - assembly__report__quast
    title: Assembly
    allOf:
      - if:
          properties:
            assembly:
              properties:
                assembly:
                  contains: "spades"
        then:
          required:
            - assembly__assembly__spades
          message: "assembly__assembly__spades is required if assembly->assembly contains spades"
      - if:
          properties:
            assembly:
              properties:
                report:
                  contains: "quast"
        then:
          required:
            - assembly__report__quast
          message: "assembly__report__quast is required if assembly->report contains quast"
      - if:
          properties:
            assembly:
              properties:
                classification:
                  type: string
                  const: "blast"
        then:
          required:
            - assembly__classification__blast
          message: "assembly__classification__blast is required if assembly->classification contains blast"

      # request resources based on specified tasks
      - if:
          properties:
            assembly:
              properties:
                classification:
                  minItems: 1
        then:
          properties:
            resources:
              required:
                - assembly__classification_mem_mb
            threads:
              required:
                - assembly__classification
      - if:
          properties:
            assembly:
              properties:
                report:
                  minItems: 1
        then:
          properties:
            threads:
              required:
                - assembly__report
  Assembly:
    additionalProperties: false
    title: Mapping
    properties:
      assembly:
        type: array
        description: "Assembly tool to use."
        items:
          type: string
          enum:
            - "spades"
        minItems: 1
      report:
        type: array
        description: "Optional. Reporting tool for assembly QC."
        default: []
        items:
          type: string
          enum:
            - "bandage"
            - "quast"
      classification:
        type: array
        description: "Optional. Classification method to use for contigs."
        default: []
        items:
          type: string
          enum:
            - "blast"
    required:
      - assembly
  AssemblyAssemblySpades:
    type: object
    additionalProperties: false
    properties:
      mode:
        type: string
        enum:
          - "standard"
          - "meta"
          - "plasmid"
          - "metaplasmid"
          - "metaviral"
          - "bio"
          - "rna"
          - "rnaviral"
        default: "standard"
        description: "if true, kraken limits RAM memory usage but sacrifices speed"
      careful:
        type: boolean
        description: "When set to true, spades tries to reduce number of mismatches and short indels, but it has longer runtime."
        default: false
    title: AssemblyAssemblySpades
  AssemblyReportQuast:
    type: object
    additionalProperties: false
    properties:
      extra:
        type: string
        default: ""
        description: "Specify any extra parameters for QUAST per manual"
      min_contig_length:
        type: integer
        description: "Minimum length in bp of contigs to evaluate in metrics"
        default: 500
    title: QuastParams
  AssemblyClassificationBlast:
    type: object
    additionalProperties: false
    properties:
      db_dir:
        type: string
        description: "Directory path where Blast DB is located, or where will be downloaded."
      query_vs_db:
        type: string
        enum:
          - "nucleotide-nucleotide"
          - "nucleotide-protein"
          - "protein-protein"
          - "protein-nucleotide"
        description: "Type of DB and type of input sequences, used to infer blast binary."
      max_number_of_hits:
        type: integer
        default: 5
      max_query_seqs:
        type: integer
        default: 2000
        Minimum: 1
        description: "Maximal number of contigs to report, ordered by their length."
      max_target_seqs:
        type: integer
        Minimum: 1
        default: 5
        description: "Maximal number of homologues from reference genomes to report."
      min_query_coverage:
        type: number
        Minimum: 0
        Maximum: 1
        default: 0.01
        description: "Show only hits that have at least this proportion of contig mapped to reference."
      seqs_per_page:
        type: integer
        Minimum: 1
        default: 100
        description: "Number of table rows (sequences) per page."
    title: BlastReportParams
  Resources:
    type: object
    additionalProperties: true
    properties:
      assembly__assembly_mem_mb:
        type: integer
        description: "Memory in MB to reserve for assembly"
        default: 2048
      assembly__classification_mem_mb:
        type: integer
        description: "Memory in MB to reserve for classification"
        default: 2048
    title: Resources
    required:
      - assembly__assembly_mem_mb
  Threads:
    type: object
    additionalProperties: true
    properties:
      assembly__assembly:
        type: integer
        default: 1
        description: "Number of threads to use for assembly"
      assembly__classification:
        type: integer
        default: 1
        description: "Number of threads to use for classification"
      assembly__report:
        type: integer
        default: 1
        description: "Number of threads to use for reporting"
    title: Threads
    required:
      - assembly__assembly
  ModuleVersions:
    type: object
    additionalProperties: true
    properties:
      reads:
        type: string
        default: 1
        pattern: "v[0-9]+.[0-9]+.[0-9]+"
        description: "Version of reads module"
    title: ModuleVersions
    required:
      - reads
