"$schema": http://json-schema.org/draft-06/schema#
"$ref": "#/definitions/AssemblyWorkflow"
definitions:
  AssemblyWorkflow:
    type: object
    additionalProperties: true
    properties:
      assembly:
        type: object
        "$ref": "#/definitions/Assembly"
      assembly__assembly__spades:
        type: object
        "$ref": "#/definitions/AssemblyAssemblySpades"
      assembly__report__quast:
        type: object
        "$ref": "#/definitions/AssemblyReportQuast"
      assembly__classification__blast:
        type: object
        "$ref": "#/definitions/AssemblyClassificationBlast"
      max_threads:
        type: integer
        description: "Number of maximum threads to use in jobs"
        default: 16
      max_mem_mb:
        type: integer
        description: "Maximum memory in megabytes to allocate for any job"
        default: 64000
      resources:
        type: object
        "$ref": "#/definitions/Resources"
      threads:
        type: object
        "$ref": "#/definitions/Threads"
      module_versions:
        type: object
        "$ref": "#/definitions/ModuleVersions"
    required:
      - resources
      - threads
      - max_threads
      - max_mem_mb
      - assembly__classification__blast
      - assembly__assembly__spades
      - assembly__report__quast
      - assembly
    title: Assembly
    allOf:
      - if:
          properties:
            assembly:
              properties:
                assembly:
                  contains: "spades"
        then:
          required:
            - assembly__assembly__spades
          message: "assembly__assembly__spades is required if assembly->assembly contains spades"
      - if:
          properties:
            assembly:
              properties:
                report:
                  contains: "quast"
        then:
          required:
            - assembly__report__quast
          message: "assembly__report__quast is required if assembly->report contains quast"
      - if:
          properties:
            assembly:
              properties:
                classification:
                  type: string
                  const: "blast"
        then:
          required:
            - assembly__classification__blast
          message: "assembly__classification__blast is required if assembly->classification contains blast"

      # request resources based on specified tasks
      - if:
          properties:
            assembly:
              properties:
                classification:
                  minItems: 1
        then:
          properties:
            resources:
              required:
                - assembly__classification_mem_mb
            threads:
              required:
                - assembly__classification
      - if:
          properties:
            assembly:
              properties:
                report:
                  minItems: 1
        then:
          properties:
            threads:
              required:
                - assembly__report
  Assembly:
    additionalProperties: false
    title: Assembly
    properties:
      assembly:
        type: array
        description: "Assembly tool to use."
        items:
          type: string
          enum:
            - "spades"
        examples: [["spades"]]
        minItems: 1
      report:
        type: array
        description: "Reporting tool for assembly QC."
        items:
          type: string
          enum:
            - "bandage"
            - "quast"
        examples: [["quast", "bandage"]]
      classification:
        type: array
        description: "Classification method to use for contigs."
        items:
          type: string
          enum:
            - "blast"
        examples: [["blast"]]
    required:
      - assembly
      - report
      - classification
  AssemblyAssemblySpades:
    type: object
    additionalProperties: false
    properties:
      mode:
        type: string
        enum:
          - "standard"
          - "meta"
          - "plasmid"
          - "metaplasmid"
          - "metaviral"
          - "bio"
          - "rna"
          - "rnaviral"
        default: "standard"
        description: "if true, kraken limits RAM memory usage but sacrifices speed"
        example: ["meta"]
      careful:
        type: boolean
        description: "When set to true, spades tries to reduce number of mismatches and short indels, but it has longer runtime."
        default: false
        example: [false]
    required:
      - mode
      - careful
    title: AssemblyAssemblySpades
  AssemblyReportQuast:
    type: object
    additionalProperties: false
    properties:
      min_contig_length:
        type: integer
        description: "Minimum length in bp of contigs to evaluate in metrics"
        default: 500
        examples: [500]
      extra:
        type: string
        default: ""
        examples: [""]
        description: "Specify any extra parameters for QUAST per manual"
    required:
      - min_contig_length
      - extra
    title: QuastParams
  AssemblyClassificationBlast:
    type: object
    additionalProperties: false
    properties:
      db_dir:
        type: string
        description: 'Directory path where Blast DB is located, or where will be downloaded. For BLAST TAG use: "18S_fungal_sequences" "Betacoronavirus" "ref_viroids_rep_genomes" "ref_viruses_rep_genomes" "refseq_select_rna" "refseq_select_prot" "refseq_protein" "refseq_rna" "16S_ribosomal_RNA" "ITS_RefSeq_Fungi" "28S_fungal_sequences" "ITS_eukaryote_sequences" "LSU_eukaryote_rRNA" "LSU_prokaryote_rRNA" "SSU_eukaryote_rRNA" "env_nt" "env_nr" "human_genome" "landmark" "mito" "mouse_genome" "nr" "nt_euk" "nt" "nt_others" "swissprot" "tsa_nr" "tsa_nt" "taxdb" "nt_prok" "nt_viruses" "pataa" "patnt" "pdbaa" "pdbnt" "ref_euk_rep_genomes" "ref_prok_rep_genomes.'
        examples: ["/data/genome/blast/{BLAST_DB_TAG}/{TIMESTAMP}"]
      query_vs_db:
        type: string
        enum:
          - "nucleotide-nucleotide"
          - "nucleotide-protein"
          - "protein-protein"
          - "protein-nucleotide"
        description: "Type of DB and type of input sequences, used to infer blast binary."
        examples: ["nucleotide-nucleotide"]
      max_number_of_hits:
        type: integer
        examples: [5]
      max_query_seqs:
        type: integer
        minimum: 1
        examples: [2000]
        description: "Maximal number of contigs to report, ordered by their length."
      max_target_seqs:
        type: integer
        minimum: 1
        examples: [5]
        description: "Maximal number of homologues from reference genomes to report."
      min_query_coverage:
        type: number
        Minimum: 0
        Maximum: 1
        examples: [0.01]
        description: "Show only hits that have at least this proportion of contig mapped to reference."
      seqs_per_page:
        type: integer
        Minimum: 1
        examples: [100]
        description: "Number of table rows (sequences) per page."
    title: BlastReportParams
  Resources:
    type: object
    additionalProperties: true
    properties:
      assembly__assembly_mem_mb:
        type: integer
        description: "Memory in MB to reserve for assembly"
        default: 64000
      assembly__classification_mem_mb:
        type: integer
        description: "Memory in MB to reserve for classification"
        default: 32000
    title: Resources
    required:
      - assembly__assembly_mem_mb
  Threads:
    type: object
    additionalProperties: true
    properties:
      assembly__assembly:
        type: integer
        default: 16
        description: "Number of threads to use for assembly"
      assembly__classification:
        type: integer
        default: 8
        description: "Number of threads to use for classification"
      assembly__report:
        type: integer
        default: 2
        description: "Number of threads to use for reporting"
    title: Threads
    required:
      - assembly__assembly
  ModuleVersions:
    type: object
    additionalProperties: true
    properties:
      reads:
        type: string
        default: "v3.4.5"
        pattern: "v[0-9]+.[0-9]+.[0-9]+"
        description: "Version of reads module"
    title: ModuleVersions
    required:
      - reads
